---
title: "KID_AI Models"
author: "Maxime Desmarets"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rpart)
library(rpart.plot)
library(e1071)
library(caret)
library(gbm)
library(pROC)
library(plotROC)

var_ai <- c(
  "age",
  "sexe",
  "nephro_ini",
  "mDialyse",
  "dDialyse",
  "trans_rein",
  "trans_rein_nbre",
  "trans_autre",
  "hepatiteB",
  "hepatiteB_active",
  "hepatiteB_chronique",
  "hepatiteC",
  "hepatiteC_active",
  "hepatiteC_chronique",
  "VIH",
  "cancer",
  "eve_cardio_acfa",
  "eve_cardio_hta",
  "eve_cardio_ic",
  "eve_cardio_nd",
  "patho_coro_idm",
  "patho_coro_rc",
  "patho_coro_angor",
  "patho_coro_ms",
  "patho_coro_nd",
  "mal_cv_avc",
  "mal_cv_ec",
  "mal_cv_tc",
  "mal_cv_nd",
  "aomi_ampu",
  "aomi_ci",
  "aomi_revascu",
  "aomi_nd",
  "patho_aort",
  "eve_pul_bpco",
  "eve_pul_emph",
  "eve_pul_ac",
  "eve_pul_ir",
  "diabete",
  "dyslipidemie",
  "hta",
  "IMC",
  "sCMV",
  "ac_antiHLA",
  "tii_induction",
  "ent_aziathioprine",
  "ent_ciclosporine",
  "ent_corticoides",
  "ent_everolimus",
  "ent_mpa",
  "ent_mmf",
  "ent_sirolimus",
  "ent_tacrolimus",
  "ent_nulojix",
  "ent_nd",
  "tii_p_antiCMV",
  "v0_tcd3_p",
  "v0_tcd3",
  "v0_tcd3_cd4_p",
  "v0_tcd3_cd4",
  "v0_tcd4_cd45ra_p",
  "v0_tcd4_cd45ra_cd31_p",
  "v0_tcd4_cd45ro_p",
  "v0_tcd3_cd8_p",
  "v0_tcd3_cd8",
  "v0_tcd3_cd8_cd16_p",
  "v0_tcd3_cd8_cd16",
  "v0_tcd3_cd8m_cd16_p",
  "v0_tcd3_cd8m_cd16",
  "v0_r_cd4_cd8",
  "v0_bcd19_p",
  "v0_bcd19",
  "v0_nk_cd56_cd3_p",
  "v0_nk_cd56_cd3",
  "v0_monocytestotaux_p",
  "v0_monocytestotaux",
  "v0_monocytesInflam_p",
  "v0_monocytesInflam",
  "rejet3y"
)

var_ai_short <- c(
  "age",
  "sexe",
  "nephro_ini",
  "diabete",
  "dyslipidemie",
  "hta",
  "IMC",
  "sCMV",
  "ac_antiHLA",
  "tii_induction",
  "ent_aziathioprine",
  "ent_ciclosporine",
  "ent_corticoides",
  "ent_everolimus",
  "ent_mpa",
  "ent_mmf",
  "ent_sirolimus",
  "ent_tacrolimus",
  "ent_nulojix",
  "ent_nd",
  "tii_p_antiCMV",
  "v0_tcd3_p",
  "v0_tcd3",
  "v0_tcd3_cd4_p",
  "v0_tcd3_cd4",
  "v0_tcd4_cd45ra_p",
  "v0_tcd4_cd45ra_cd31_p",
  "v0_tcd4_cd45ro_p",
  "v0_tcd3_cd8_p",
  "v0_tcd3_cd8",
  "v0_tcd3_cd8_cd16_p",
  "v0_tcd3_cd8_cd16",
  "v0_tcd3_cd8m_cd16_p",
  "v0_tcd3_cd8m_cd16",
  "v0_r_cd4_cd8",
  "v0_bcd19_p",
  "v0_bcd19",
  "v0_nk_cd56_cd3_p",
  "v0_nk_cd56_cd3",
  "v0_monocytestotaux_p",
  "v0_monocytestotaux",
  "v0_monocytesInflam_p",
  "v0_monocytesInflam",
  "rejet3y"
)


var_ai_mini <- c(
  "age",
  "sexe",
  "v0_tcd3_p",
  "v0_tcd3",
  "v0_tcd3_cd4_p",
  "v0_tcd3_cd4",
  "v0_tcd4_cd45ra_p",
  "v0_tcd4_cd45ra_cd31_p",
  "v0_tcd4_cd45ro_p",
  "v0_tcd3_cd8_p",
  "v0_tcd3_cd8",
  "v0_tcd3_cd8_cd16_p",
  "v0_tcd3_cd8_cd16",
  "v0_tcd3_cd8m_cd16_p",
  "v0_tcd3_cd8m_cd16",
  "v0_r_cd4_cd8",
  "v0_bcd19_p",
  "v0_bcd19",
  "v0_nk_cd56_cd3_p",
  "v0_nk_cd56_cd3",
  "v0_monocytestotaux_p",
  "v0_monocytestotaux",
  "v0_monocytesInflam_p",
  "v0_monocytesInflam",
  "rejet3y"
)

orly_ai <- orly |> 
  select(all_of(var_ai)) |> 
  drop_na() |> 
  mutate(rejet3y = relevel(as.factor(rejet3y), ref="0"))

# Response
summary(orly_ai$rejet3y)

# Missing data
apply(orly_ai, 2, FUN = function(x){sum(is.na(x))}) # Type of variable

dim(orly_ai)

# Standardization
orly_ai_std <- orly_ai %>% mutate(across(v0_tcd3_p:v0_monocytesInflam, scale))

# Plot
plot_data_std <- orly_ai_std |> pivot_longer(v0_tcd3_p:v0_monocytesInflam)

ggplot(plot_data_std, aes(value, fill = rejet3y)) +
  geom_histogram() +
  facet_wrap(. ~ name, scales = "free")

# Training / testing set
set.seed(5678)
select <- sample(1:nrow(orly_ai_std), size = 0.7*nrow(orly))
train <- orly_ai_std[select,]
test <- orly_ai_std[-select,]
```
# CART
## Model
```{r}
tree_max <- rpart(rejet3y ~ . , data = train, cp = 0.000001, minsplit = 5)
plotcp(tree_max)
cp_opt <- tree_max$cptable[which.min(tree_max$cptable[,'xerror']), 'CP']
tree_opt <- rpart::prune(tree_max, cp = cp_opt)
rpart.plot::prp(tree_opt)
```
## Performance
```{r}
pred_tree_train <- predict(tree_opt, newdata = train, type="class")
pred_tree_test <- predict(tree_opt, newdata = test, type="class")

roc_data_train <- data.frame(tree_train = pred_tree_train, obs = train$rejet3y)
roc_data_train <- roc_data_train %>% gather(key = Methode, value = score, tree_train)
roc_data_train |> ggplot() + aes(d=obs, m=score, color=Methode) + geom_roc() + theme_classic()

roc_data_train %>% filter(Methode=="tree") %>% summarize(AUC = pROC::auc(obs, as.numeric(score)))
```

# Random Forest
## Model
```{r}
library(randomForest)
forest <- randomForest(as.factor(rejet3y) ~ ., data = train)
forest
plot(forest)
```

## Grid
```{r}
grille.mtry <- data.frame(mtry=seq(1,79,by=3))
library(caret)
ctrl <- trainControl(method="oob")
library(doParallel)    # pour paralléliser
cl <- makePSOCKcluster(8)
registerDoParallel(cl)     
set.seed(12345)
sel.mtry <- train(as.factor(rejet3y) ~ . , data = train, method="rf", trControl = ctrl, tuneGrid = grille.mtry)
sel.mtry
stopCluster(cl)  
```

## Performance
```{r}
set.seed(5432)
foret1 <- randomForest(rejet3y ~ .,data = train, mtry=1)

pred_test <- predict(foret1, newdata = test)
pred_test[1:10]

prob_test <- predict(foret1, newdata = test, type = "prob")
prob_test[1:10,]

roc_data <- roc(test$rejet3y, as.numeric(pred_test))
plot(roc_data, print.auc=TRUE,print.auc.cex=0.5,print.auc.x=0.4,print.auc.y=0.3) 
```
# SVM
## Model RBF
```{r}
tune_rbf <- tune.svm(rejet3y ~ ., data = train,  kernel = "radial", gamma = 2^(-4:4), cost = 10^(-1:4))
summary(tune_rbf)
plot(tune_rbf)

# Best rbf model
svm_rbf <- svm(rejet3y ~ ., data = train, kernel = "radial", cost = .1, gamma = 0.0625, type = "C-classification", scale = FALSE)
summary(svm_rbf)
```

## RBF Performance train
```{r}
table(train$rejet3y, svm_rbf$fitted)

confmat_train <- confusionMatrix(svm_rbf$fitted, train$rejet3y, positive = "1")
confmat_train
```

## Model Poly
```{r}
tune_poly <- tune.svm(rejet3y ~ ., data = train,  kernel = "polynomial", degree = 3:4, gamma = 2^(-4:4), cost = 10^(-1:4))
summary(tune_poly)
#plot(tune_poly)

# Best poly model
svm_poly <- svm(rejet3y ~ ., data = train, kernel = "polynomial", degree = 3, cost = .1, gamma = 0.0625, type = "C-classification", scale = FALSE)
summary(svm_poly)
```
## SVM Poly Performance train
```{r}
table(train$rejet3y, svm_poly$fitted)

confmat_train <- confusionMatrix(svm_poly$fitted, train$rejet3y, positive = "1")
confmat_train
```

## SVM Poly Performance test
```{r}
pred <- predict(svm_poly, newdata = test)
table(test$rejet3y, pred)

confmat_train <- confusionMatrix(pred, test$rejet3y, positive = "1")
confmat_train
```
# Gradient boosting
```{r}
set.seed(1234)
gbm_ada <- gbm(rejet3y ~ ., data = train, cv.folds = 5, distribution="adaboost", shrinkage=0.01, n.trees=3000)
gbm_logit <- gbm(rejet3y ~ ., data = train, cv.folds = 5, distribution="bernoulli", shrinkage=0.05, n.trees=3000)

# gbm.perf: to estimate error associated to the
# loss function
Mopt_ada <- gbm.perf(gbm_ada, method="cv")
Mopt_logit <- gbm.perf(gbm_logit, method="cv")
```

